name: Deploy QR Checkin System

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: '6.0'
          mongodb-port: 27017
          
      - name: Create storage directories
        run: |
          mkdir -p data
          mkdir -p log
          
      - name: Configure environment
        run: |
          echo "DEPLOY_ENV=${{ secrets.DEPLOY_ENV || 'production' }}" > .env
          echo "DEBUG=${{ secrets.DEBUG || 'False' }}" >> .env
          echo "SERVER_NAME=0.0.0.0" >> .env
          echo "PORT_NUMBER=${{ secrets.PORT_NUMBER || '5050' }}" >> .env
          echo "ADMIN_SECRET_KEY=${{ secrets.ADMIN_SECRET_KEY }}" >> .env
          echo "USER_SECRET_KEY=${{ secrets.USER_SECRET_KEY }}" >> .env
          echo "DATA_DIR=./data" >> .env
          echo "LOG_DIR=./log" >> .env
          echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING || 'mongodb://localhost:27017/' }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME || 'qr_checkin_system' }}" >> .env
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull
            pip install -r requirements.txt
            # Add commands to restart your application
            # e.g., systemctl restart your_service or pm2 restart your_app
